//
//  Quotes.swift
//  todoTask
//
//  Created by Jana Abdulaziz Malibari on 14/02/2026.
//

import Foundation

enum Quotes {
    static let all: [String] = [
        "Creativity begins where certainty ends.",
        "Your imagination is not a distraction — it’s a direction.",
        "Build what doesn’t exist yet.",
        "The blank page is a challenge, not a threat.",
        "Don’t wait for inspiration. Manufacture it.",
        "Create badly. Then create better.",
        "Ideas grow when you give them deadlines.",
        "Make something today your past self couldn’t.",
        "Curiosity is your creative engine. Feed it.",
        "Stop consuming. Start producing.",
        "Your weirdness is your competitive advantage.",
        "If it scares you creatively, you’re close to something good.",
        "Originality is courage in action.",
        "Inspiration follows effort, not the other way around.",
        "Creativity is discipline disguised as play.",
        "Don’t polish what you haven’t built.",
        "Small ideas become powerful when executed.",
        "You don’t need permission to create.",
        "Every masterpiece started as a rough draft.",
        "Constraints sharpen imagination.",
        "Your taste improves by building, not judging.",
        "The world doesn’t need safe ideas.",
        "Momentum beats motivation.",
        "Sketch it. Prototype it. Ship it.",
        "Progress > perfection.",
        "Ideas are cheap. Execution is rare.",
        "Doubt is part of the creative process.",
        "Make something that solves your own problem.",
        "Creativity thrives on consistency.",
        "Start before you feel ready.",
        "Inspiration hides inside action.",
        "Build the version you wish existed.",
        "Your first attempt is data, not destiny.",
        "Creative confidence is earned through repetition.",
        "Risk boring people. Avoid boring yourself.",
        "Learn fast. Create faster.",
        "You improve by shipping, not by waiting.",
        "Experiment wildly. Refine strategically.",
        "Your perspective is your power.",
        "Make the invisible visible.",
        "Don’t chase trends. Build standards.",
        "Your voice matters more than your tools.",
        "Done is better than imagined.",
        "Every draft teaches you something.",
        "Create what excites you at 2 a.m.",
        "Skill grows where effort goes.",
        "Make fear your creative fuel.",
        "Discipline creates freedom.",
        "Creative work compounds over time.",
        "Build daily. Think long-term.",
        "If it feels obvious, make it anyway.",
        "Turn frustration into innovation.",
        "Start messy. Finish strong.",
        "Your ideas deserve execution.",
        "Focus creates depth. Depth creates value.",
        "Be consistent enough to surprise yourself.",
        "Mastery begins with repetition.",
        "You don’t find style — you develop it.",
        "Your next idea depends on today’s effort.",
        "Action silences overthinking.",
        "Make bold choices. Refine later.",
        "Creativity rewards persistence.",
        "Don’t scroll past your own potential.",
        "The best ideas are often uncomfortable.",
        "Quantity leads to quality.",
        "Your imagination is underused — prove it wrong.",
        "What you build today shapes tomorrow’s confidence.",
        "Creativity is a muscle. Train it.",
        "Turn “what if” into “why not.”",
        "Progress hides inside repetition.",
        "If you can imagine it, prototype it.",
        "Build systems, not excuses.",
        "Ideas need action to survive.",
        "Creativity grows in uncomfortable territory.",
        "Make something that makes you proud.",
        "Learn the rules. Break them wisely.",
        "Don’t wait for clarity. Create it.",
        "Your creativity is your responsibility.",
        "Inspiration rewards commitment.",
        "Make the complex simple.",
        "Push past average.",
        "Create before you consume.",
        "Great work starts with showing up.",
        "Curiosity beats talent.",
        "Consistency builds confidence.",
        "Imperfect work beats perfect intention.",
        "Innovation begins with dissatisfaction.",
        "Design the future you want to see.",
        "Build relentlessly. Improve intentionally.",
        "The process is the product.",
        "Creativity is solving problems differently.",
        "Think deeper. Build smarter.",
        "Ship first. Optimize later.",
        "Your best idea is still ahead of you.",
        "Keep creating until it clicks.",
        "Turn ideas into impact.",
        "Make art. Make code. Make change.",
        "Question everything. Build something.",
        "Creative people aren’t lucky — they’re consistent.",
        "Start now. Adjust later."
    ]
    
    static func random() -> String? {
        all.randomElement()
    }
}
